-- DISPOSABLE TEST TARGET ONLY. Missing pre-repository base schema, not a release migration.
-- The local runner checks its exact loopback target/container before executing this file.
begin;
create schema discovery_test_private;
revoke all on schema discovery_test_private from public, anon, authenticated;
create table discovery_test_private.marker (identity text primary key);
insert into discovery_test_private.marker values ('lumiscore-pr8-synthetic-v1');
create table public.authors (
  id bigint generated by default as identity primary key,
  name text not null,
  open_library_id text unique
);
create table public.works (
  id bigint generated by default as identity primary key,
  title text not null,
  author_id bigint references public.authors(id),
  first_publish_year integer,
  open_library_id text unique,
  cover_id bigint
);
create table public.editions (
  id bigint generated by default as identity primary key,
  work_id bigint not null references public.works(id),
  title text,
  language text,
  open_library_edition_id text unique,
  isbn_10 text,
  isbn_13 text,
  publisher text,
  publish_date text,
  cover_id bigint
);
alter table public.authors enable row level security;
alter table public.works enable row level security;
alter table public.editions enable row level security;
revoke all on public.authors,public.works,public.editions from public,anon,authenticated;
grant select on public.authors,public.works,public.editions to anon,authenticated;
grant all on public.authors,public.works,public.editions to service_role;
grant usage,select on all sequences in schema public to service_role;
create policy authors_test_public_read on public.authors for select to anon,authenticated using(true);
create policy works_test_public_read on public.works for select to anon,authenticated using(true);
create policy editions_test_public_read on public.editions for select to anon,authenticated using(true);
commit;
