import type { SeedBook } from './open-library-seeds.ts';
import {
  NETHERLANDS_NATIVE_DISPOSITIONS,
  type NativeSeedMetadata,
} from './lumiscore-native-seeds-nl.ts';

export const NETHERLANDS_SEED_CATEGORIES = [
  'literary-general-fiction',
  'thriller-crime',
  'young-adult-children',
  'non-fiction',
  'romance-feelgood',
  'classics',
  'fantasy-science-fiction',
] as const;

export type NetherlandsSeedCategory =
  (typeof NETHERLANDS_SEED_CATEGORIES)[number];

export type NetherlandsSeedBook = SeedBook & {
  netherlandsCategory: NetherlandsSeedCategory;
  collection: 'netherlands-core' | 'suzanne-vermeer';
  manualReviewCandidates?: readonly string[];
  manualReviewReason?: string;
  nativeMetadata?: NativeSeedMetadata;
  importDisposition?: 'NEEDS_MORE_RESEARCH' | 'REJECT';
  dispositionReason?: string;
};

const seedKey = (title: string, author: string) => `${title}\u0000${author}`;

const OPEN_LIBRARY_MATCH_OVERRIDES: Readonly<
  Record<
    string,
    Pick<SeedBook, 'alternateTitles' | 'preferredDisplayTitle'>
  >
> = {
  "Abeltje\u0000Annie M.G. Schmidt": {
    alternateTitles: ['Abeltje (Jeugdsalamander)'],
    preferredDisplayTitle: 'Abeltje',
  },
  "Anna\u0000Annejet van der Zijl": {
    alternateTitles: ['Anna - Het leven van Annie M.G. Schmidt'],
    preferredDisplayTitle: 'Anna',
  },
  "De meeste mensen deugen\u0000Rutger Bregman": {
    alternateTitles: ['Humankind', 'Humankind: A Hopeful History'],
    preferredDisplayTitle: 'De meeste mensen deugen',
  },
  "Morele ambitie\u0000Rutger Bregman": {
    alternateTitles: [
      'Moral Ambition',
      'Moral Ambition: Stop Wasting Your Talent and Start Making a Difference',
    ],
    preferredDisplayTitle: 'Morele ambitie',
  },
  "Honderd uur nacht\u0000Anna Woltz": {
    alternateTitles: ['Hundred Hours of Night', 'Hundert Stunden Nacht'],
    preferredDisplayTitle: 'Honderd uur nacht',
  },
  "De tunnel\u0000Anna Woltz": {
    alternateTitles: ['Tunnel'],
    preferredDisplayTitle: 'De tunnel',
  },
  "Het zijn net mensen\u0000Joris Luyendijk": {
    alternateTitles: [
      'Zijn net mensen',
      'Zijn net mensen: misrepresenting the Middle East',
    ],
    preferredDisplayTitle: 'Het zijn net mensen',
  },
  "Ons creatieve brein\u0000Dick Swaab": {
    alternateTitles: ['Unser kreatives Gehirn'],
    preferredDisplayTitle: 'Ons creatieve brein',
  },
};

const OPEN_LIBRARY_WORK_IDS: Readonly<Record<string, string>> = {
  "De geruchten\u0000Hugo Claus": "OL34920661W",
  "De verwondering\u0000Hugo Claus": "OL15056319W",
  "Het volgende verhaal\u0000Cees Nooteboom": "OL643733W",
  "Het woud der verwachting\u0000Hella S. Haasse": "OL34953098W",
  "Problemski Hotel\u0000Dimitri Verhulst": "OL866308W",
  "Opwaaiende zomerjurken\u0000Oek de Jong": "OL1687249W",
  "Nieuwe buren\u0000Saskia Noort": "OL8937618W",
  "Bonuskind\u0000Saskia Noort": "OL26420829W",
  "Rendez-vous\u0000Esther Verhoef": "OL19335865W",
  "Alles te verliezen\u0000Esther Verhoef": "OL34876668W",
  "Het laatste offer\u0000Simone van der Vlugt": "OL24269387W",
  "Herfstlied\u0000Simone van der Vlugt": "OL19943872W",
  "De macht van meneer Miller\u0000Charles den Tex": "OL26180417W",
  "Cel\u0000Charles den Tex": "OL34875672W",
  "Wachtwoord\u0000Charles den Tex": "OL33763745W",
  "Pluk van de Petteflet\u0000Annie M.G. Schmidt": "OL34952258W",
  "Abeltje\u0000Annie M.G. Schmidt": "OL39413096W",
  "Wiplala\u0000Annie M.G. Schmidt": "OL3173349W",
  "Kinderen van Moeder Aarde\u0000Thea Beckman": "OL24343787W",
  "Lover of loser\u0000Carry Slee": "OL26178174W",
  "Kappen!\u0000Carry Slee": "OL20660640W",
  "Foeksia de miniheks\u0000Paul van Loon": "OL35159241W",
  "Weerwolvenbos\u0000Paul van Loon": "OL34942140W",
  "Het boek van alle dingen\u0000Guus Kuijer": "OL34875388W",
  "Achtste-groepers huilen niet\u0000Jacques Vriens": "OL24360162W",
  "Oorlogsgeheimen\u0000Jacques Vriens": "OL29233044W",
  "De brug\u0000Geert Mak": "OL20112304W",
  "Gratis geld voor iedereen\u0000Rutger Bregman": "OL31712603W",
  "De meeste mensen deugen\u0000Rutger Bregman": "OL20726133W",
  "Morele ambitie\u0000Rutger Bregman": "OL43449005W",
  "Anna\u0000Annejet van der Zijl": "OL9096581W",
  "Sonny Boy\u0000Annejet van der Zijl": "OL759017W",
  "De Amerikaanse prinses\u0000Annejet van der Zijl": "OL24447276W",
  "Anna Boom\u0000Judith Koelemeijer": "OL34536597W",
  "Revolusi\u0000David Van Reybrouck": "OL24234444W",
  "Wij zijn ons brein\u0000Dick Swaab": "OL24713032W",
  "De Bourgondiërs\u0000Bart Van Loo": "OL34943539W",
  "De omwenteling\u0000Suzanna Jansen": "OL34961957W",
  "Zwaar verliefd!\u0000Chantal van Gastel": "OL34869705W",
  "De kleine Johannes\u0000Frederik van Eeden": "OL27339889W",
  "Pijpelijntjes\u0000Jacob Israël de Haan": "OL3698641W",
  "Bint\u0000F. Bordewijk": "OL37342453W",
  "Kaas\u0000Willem Elsschot": "OL1232228W",
  "Het dwaallicht\u0000Willem Elsschot": "OL23961881W",
  "Ivanov\u0000Hanna Bervoets": "OL44206159W",
  "Sneeuwexpress\u0000Suzanne Vermeer": "OL30710666W",
  "Honderd uur nacht\u0000Anna Woltz": "OL21294698W",
  "De tunnel\u0000Anna Woltz": "OL42541061W",
  "Het zijn net mensen\u0000Joris Luyendijk": "OL15082537W",
  "Ons creatieve brein\u0000Dick Swaab": "OL20921817W",
  "De ontdekking van de hemel\u0000Harry Mulisch": "OL659062W",
  "De aanslag\u0000Harry Mulisch": "OL16253633W",
  "Twee vrouwen\u0000Harry Mulisch": "OL659103W",
  "Het stenen bruidsbed\u0000Harry Mulisch": "OL659052W",
  "De procedure\u0000Harry Mulisch": "OL659063W",
  "De donkere kamer van Damokles\u0000Willem Frederik Hermans": "OL109957W",
  "Nooit meer slapen\u0000Willem Frederik Hermans": "OL109959W",
  "Onder professoren\u0000Willem Frederik Hermans": "OL15250238W",
  "Au pair\u0000Willem Frederik Hermans": "OL109948W",
  "Herinneringen van een engelbewaarder\u0000Willem Frederik Hermans": "OL11780437W",
  "De avonden\u0000Gerard Reve": "OL699606W",
  "Op weg naar het einde\u0000Gerard Reve": "OL699602W",
  "Nader tot U\u0000Gerard Reve": "OL699601W",
  "Moeder en zoon\u0000Gerard Reve": "OL699585W",
  "Bezorgde ouders\u0000Gerard Reve": "OL699604W",
  "Het verdriet van België\u0000Hugo Claus": "OL165559W",
  "Omtrent Deedee\u0000Hugo Claus": "OL11012088W",
  "Rituelen\u0000Cees Nooteboom": "OL643737W",
  "Allerzielen\u0000Cees Nooteboom": "OL643724W",
  "Paradijs verloren\u0000Cees Nooteboom": "OL643732W",
  "Oeroeg\u0000Hella S. Haasse": "OL1348412W",
  "Heren van de thee\u0000Hella S. Haasse": "OL1348408W",
  "De scharlaken stad\u0000Hella S. Haasse": "OL1348407W",
  "Het diner\u0000Herman Koch": "OL2486917W",
  "Zomerhuis met zwembad\u0000Herman Koch": "OL16021831W",
  "Geachte heer M.\u0000Herman Koch": "OL17321275W",
  "De greppel\u0000Herman Koch": "OL20799471W",
  "Joe Speedboot\u0000Tommy Wieringa": "OL14988838W",
  "Dit zijn de namen\u0000Tommy Wieringa": "OL20393395W",
  "Caesarion\u0000Tommy Wieringa": "OL14988837W",
  "De heilige Rita\u0000Tommy Wieringa": "OL19740455W",
  "La Superba\u0000Ilja Leonard Pfeijffer": "OL30706292W",
  "Grand Hotel Europa\u0000Ilja Leonard Pfeijffer": "OL24320267W",
  "Alkibiades\u0000Ilja Leonard Pfeijffer": "OL43774423W",
  "Peachez, een romance\u0000Ilja Leonard Pfeijffer": "OL20214285W",
  "Blauwe maandagen\u0000Arnon Grunberg": "OL850954W",
  "Tirza\u0000Arnon Grunberg": "OL850975W",
  "De asielzoeker\u0000Arnon Grunberg": "OL850956W",
  "Moedervlekken\u0000Arnon Grunberg": "OL20815006W",
  "Het smelt\u0000Lize Spit": "OL34323377W",
  "Ik ben er niet\u0000Lize Spit": "OL24326452W",
  "De helaasheid der dingen\u0000Dimitri Verhulst": "OL15114233W",
  "De laatkomer\u0000Dimitri Verhulst": "OL17038431W",
  "Kom hier dat ik u kus\u0000Griet Op de Beeck": "OL24318637W",
  "Het beste wat we hebben\u0000Griet Op de Beeck": "OL24440493W",
  "Oorlog en terpentijn\u0000Stefan Hertmans": "OL23296728W",
  "De bekeerlinge\u0000Stefan Hertmans": "OL24320466W",
  "De avond is ongemak\u0000Marieke Lucas Rijneveld": "OL19740451W",
  "Mijn lieve gunsteling\u0000Marieke Lucas Rijneveld": "OL24147196W",
  "Wees onzichtbaar\u0000Murat Isik": "OL24328099W",
  "Verloren grond\u0000Murat Isik": "OL30953755W",
  "Indische duinen\u0000Adriaan van Dis": "OL9960466W",
  "Familieziek\u0000Adriaan van Dis": "OL2415116W",
  "Een vlucht regenwulpen\u0000Maarten 't Hart": "OL719962W",
  "Het woeden der gehele wereld\u0000Maarten 't Hart": "OL719963W",
  "Bezonken rood\u0000Jeroen Brouwers": "OL702827W",
  "De wetten\u0000Connie Palmen": "OL748333W",
  "De zwarte met het witte hart\u0000Arthur Japin": "OL660526W",
  "Terug naar de kust\u0000Saskia Noort": "OL24302287W",
  "De eetclub\u0000Saskia Noort": "OL20906472W",
  "De verbouwing\u0000Saskia Noort": "OL17366771W",
  "Koorts\u0000Saskia Noort": "OL19964029W",
  "Debet\u0000Saskia Noort": "OL24173760W",
  "Huidpijn\u0000Saskia Noort": "OL44255136W",
  "Stromboli\u0000Saskia Noort": "OL24319402W",
  "Close-up\u0000Esther Verhoef": "OL18647037W",
  "Déjà vu\u0000Esther Verhoef": "OL24721289W",
  "Tegenlicht\u0000Esther Verhoef": "OL23217732W",
  "De kraamhulp\u0000Esther Verhoef": "OL24326401W",
  "Lieve mama\u0000Esther Verhoef": "OL25301223W",
  "Nazomer\u0000Esther Verhoef": "OL24613256W",
  "De nachtdienst\u0000Esther Verhoef": "OL34951855W",
  "De reünie\u0000Simone van der Vlugt": "OL20936876W",
  "Schaduwzuster\u0000Simone van der Vlugt": "OL17352652W",
  "Blauw water\u0000Simone van der Vlugt": "OL36528502W",
  "Op klaarlichte dag\u0000Simone van der Vlugt": "OL24290121W",
  "Vrijdag\u0000Loes den Hollander": "OL27677388W",
  "Zwanenzang\u0000Loes den Hollander": "OL28166179W",
  "Dwaalspoor\u0000Loes den Hollander": "OL24650467W",
  "Voorbedacht\u0000Loes den Hollander": "OL27280970W",
  "Het bloemenmeisje\u0000Anya Niewierra": "OL44488387W",
  "De Camino\u0000Anya Niewierra": "OL30941021W",
  "De nomade\u0000Anya Niewierra": "OL44255134W",
  "Daglicht\u0000Marion Pauw": "OL27974484W",
  "Minoes\u0000Annie M.G. Schmidt": "OL3173342W",
  "Otje\u0000Annie M.G. Schmidt": "OL3173344W",
  "De brief voor de koning\u0000Tonke Dragt": "OL3793472W",
  "Geheimen van het Wilde Woud\u0000Tonke Dragt": "OL3793463W",
  "De torens van februari\u0000Tonke Dragt": "OL3793475W",
  "Ogen van tijgers\u0000Tonke Dragt": "OL3793466W",
  "Aan de andere kant van de deur\u0000Tonke Dragt": "OL3793465W",
  "De zevensprong\u0000Tonke Dragt": "OL3793474W",
  "Kruistocht in spijkerbroek\u0000Thea Beckman": "OL1736494W",
  "Geef me de ruimte!\u0000Thea Beckman": "OL17211843W",
  "Triomf van de verschroeide aarde\u0000Thea Beckman": "OL31292457W",
  "Het rad van fortuin\u0000Thea Beckman": "OL1736489W",
  "Het helse paradijs\u0000Thea Beckman": "OL24542304W",
  "Het Gulden Vlies van Thule\u0000Thea Beckman": "OL45476471W",
  "Hasse Simonsdochter\u0000Thea Beckman": "OL1736487W",
  "Koning van Katoren\u0000Jan Terlouw": "OL3681910W",
  "Oorlogswinter\u0000Jan Terlouw": "OL3681911W",
  "Briefgeheim\u0000Jan Terlouw": "OL3681906W",
  "Oosterschelde windkracht 10\u0000Jan Terlouw": "OL3681914W",
  "Pjotr\u0000Jan Terlouw": "OL3681915W",
  "Zoektocht in Katoren\u0000Jan Terlouw": "OL25299914W",
  "Spijt!\u0000Carry Slee": "OL973945W",
  "Afblijven\u0000Carry Slee": "OL973937W",
  "Razend\u0000Carry Slee": "OL23780645W",
  "Paniek\u0000Carry Slee": "OL26180341W",
  "Brainwash\u0000Carry Slee": "OL24739344W",
  "De griezelbus\u0000Paul van Loon": "OL26376875W",
  "Dolfje Weerwolfje\u0000Paul van Loon": "OL2286363W",
  "Meester Kikker\u0000Paul van Loon": "OL2286364W",
  "Raveleijn\u0000Paul van Loon": "OL20421257W",
  "Op je kop in de prullenbak\u0000Guus Kuijer": "OL4390388W",
  "Krassen in het tafelblad\u0000Guus Kuijer": "OL4390386W",
  "Voor altijd samen, amen\u0000Guus Kuijer": "OL4390391W",
  "Gips\u0000Anna Woltz": "OL24395092W",
  "Alaska\u0000Anna Woltz": "OL19735880W",
  "Lampje\u0000Annet Schaap": "OL19735887W",
  "De kinderen van het Achtste Woud\u0000Els Pelgrom": "OL1664786W",
  "Kleine Sofie en Lange Wapper\u0000Els Pelgrom": "OL1664792W",
  "Hoe God verdween uit Jorwerd\u0000Geert Mak": "OL931628W",
  "De eeuw van mijn vader\u0000Geert Mak": "OL931621W",
  "In Europa\u0000Geert Mak": "OL931630W",
  "Reizen zonder John\u0000Geert Mak": "OL23233125W",
  "Grote verwachtingen\u0000Geert Mak": "OL24591945W",
  "De geschiedenis van de vooruitgang\u0000Rutger Bregman": "OL20783434W",
  "Jagtlust\u0000Annejet van der Zijl": "OL759018W",
  "Bernhard\u0000Annejet van der Zijl": "OL33367409W",
  "Gerard Heineken\u0000Annejet van der Zijl": "OL23358669W",
  "Fortuna's kinderen\u0000Annejet van der Zijl": "OL30941109W",
  "Het zwijgen van Maria Zachea\u0000Judith Koelemeijer": "OL9100673W",
  "Hemelvaart\u0000Judith Koelemeijer": "OL23127200W",
  "Dit kan niet waar zijn\u0000Joris Luyendijk": "OL22937543W",
  "De zeven vinkjes\u0000Joris Luyendijk": "OL28216089W",
  "Congo\u0000David Van Reybrouck": "OL19980745W",
  "Tegen verkiezingen\u0000David Van Reybrouck": "OL32958567W",
  "'t Hooge Nest\u0000Roxane van Iperen": "OL21210227W",
  "Het geluk van Limburg\u0000Marcia Luyten": "OL31276092W",
  "Het pauperparadijs\u0000Suzanna Jansen": "OL29298344W",
  "Komt een vrouw bij de dokter\u0000Kluun": "OL33789130W",
  "De weduwnaar\u0000Kluun": "OL26189493W",
  "Pogingen iets van het leven te maken\u0000Hendrik Groen": "OL19712767W",
  "Zolang er leven is\u0000Hendrik Groen": "OL19740472W",
  "Leven en laten leven\u0000Hendrik Groen": "OL34310983W",
  "Opgewekt naar de eindstreep\u0000Hendrik Groen": "OL24341496W",
  "Zwaar beproefd!\u0000Chantal van Gastel": "OL26181155W",
  "Geknipt voor jou\u0000Chantal van Gastel": "OL33869770W",
  "Zomer in New York\u0000Chantal van Gastel": "OL24670307W",
  "Glazuur\u0000Lisette Jonkman": "OL26184739W",
  "Verkikkerd\u0000Lisette Jonkman": "OL24522697W",
  "Verslingerd\u0000Lisette Jonkman": "OL26182328W",
  "Enkeltje Ierland\u0000Charlotte de Monchy": "OL24400584W",
  "Nee heb je\u0000Charlotte de Monchy": "OL24326852W",
  "Max Havelaar\u0000Multatuli": "OL38786499W",
  "Eline Vere\u0000Louis Couperus": "OL1456910W",
  "De stille kracht\u0000Louis Couperus": "OL1456909W",
  "Van oude mensen, de dingen die voorbijgaan\u0000Louis Couperus": "OL1456917W",
  "Noodlot\u0000Louis Couperus": "OL35409751W",
  "Van de koele meren des doods\u0000Frederik van Eeden": "OL11928480W",
  "De uitvreter\u0000Nescio": "OL2795316W",
  "Titaantjes\u0000Nescio": "OL2795318W",
  "Karakter\u0000F. Bordewijk": "OL1355544W",
  "Knorrende beesten\u0000F. Bordewijk": "OL14904174W",
  "Terug tot Ina Damman\u0000Simon Vestdijk": "OL812225W",
  "De koperen tuin\u0000Simon Vestdijk": "OL812194W",
  "De tienduizend dingen\u0000Maria Dermoût": "OL45328704W",
  "Villa des Roses\u0000Willem Elsschot": "OL1232227W",
  "Kees de jongen\u0000Theo Thijssen": "OL3065424W",
  "HEX\u0000Thomas Olde Heuvelt": "OL20027994W",
  "Echo\u0000Thomas Olde Heuvelt": "OL25444278W",
  "Orakel\u0000Thomas Olde Heuvelt": "OL30337412W",
  "November\u0000Thomas Olde Heuvelt": "OL34958609W",
  "Alles wat er was\u0000Hanna Bervoets": "OL23118085W",
  "En ik herinner me Titus Broederland\u0000Auke Hulst": "OL34949537W",
  "Quarantaine\u0000Wytske Versteeg": "OL45029610W",
  "KliFi\u0000Adriaan van Dis": "OL43861237W",
  "All-inclusive\u0000Suzanne Vermeer": "OL24452795W",
  "De vlucht\u0000Suzanne Vermeer": "OL20778158W",
  "Zomertijd\u0000Suzanne Vermeer": "OL34868142W",
  "Cruise\u0000Suzanne Vermeer": "OL21609237W",
  "Après-ski\u0000Suzanne Vermeer": "OL17616820W",
  "De suite\u0000Suzanne Vermeer": "OL20451450W",
  "Zwarte piste\u0000Suzanne Vermeer": "OL26189670W",
  "Bella Italia\u0000Suzanne Vermeer": "OL21609238W",
  "Bon Bini Beach\u0000Suzanne Vermeer": "OL21609239W",
  "Noorderlicht\u0000Suzanne Vermeer": "OL34826276W",
  "Het chalet\u0000Suzanne Vermeer": "OL33760020W",
  "Route du soleil\u0000Suzanne Vermeer": "OL26180499W",
  "Goudkust\u0000Suzanne Vermeer": "OL24702185W",
  "Mont Blanc\u0000Suzanne Vermeer": "OL26183481W",
  "Costa del Sol\u0000Suzanne Vermeer": "OL24422086W",
  "Sneeuwengelen\u0000Suzanne Vermeer": "OL20778157W",
  "Hittegolf\u0000Suzanne Vermeer": "OL24500050W",
  "Lawinegevaar\u0000Suzanne Vermeer": "OL33760983W",
  "Het paradijs\u0000Suzanne Vermeer": "OL30599005W",
  "Super de luxe\u0000Suzanne Vermeer": "OL24341599W",
  "IJskoud\u0000Suzanne Vermeer": "OL24348751W",
  "Winternacht\u0000Suzanne Vermeer": "OL19740461W",
  "Het strandhuis\u0000Suzanne Vermeer": "OL24341736W",
  "Roadtrip\u0000Suzanne Vermeer": "OL27730112W",
  "Spoorloos\u0000Suzanne Vermeer": "OL42854974W",
  "Flamingo Beach\u0000Suzanne Vermeer": "OL44984219W",
};

const OPEN_LIBRARY_AUTHOR_IDS: Readonly<Record<string, string>> = {
  "Bonuskind\u0000Saskia Noort": 'OL3091091A',
  "Alles te verliezen\u0000Esther Verhoef": 'OL3087562A',
  "Foeksia de miniheks\u0000Paul van Loon": 'OL300379A',
  "Weerwolvenbos\u0000Paul van Loon": 'OL300379A',
  "Het boek van alle dingen\u0000Guus Kuijer": 'OL865499A',
  "Achtste-groepers huilen niet\u0000Jacques Vriens": 'OL200176A',
  "Oorlogsgeheimen\u0000Jacques Vriens": 'OL200176A',
  "Zwaar verliefd!\u0000Chantal van Gastel": 'OL9301506A',
  "Sneeuwexpress\u0000Suzanne Vermeer": 'OL7535086A',
  "Kinderen van Moeder Aarde\u0000Thea Beckman": 'OL200233A',
  "Abeltje\u0000Annie M.G. Schmidt": 'OL507781A',
  "Wiplala\u0000Annie M.G. Schmidt": 'OL507781A',
  "November\u0000Thomas Olde Heuvelt": 'OL7482809A',
  "Pluk van de Petteflet\u0000Annie M.G. Schmidt": 'OL507781A',
};

const MANUAL_REVIEWS: Readonly<
  Record<string, { candidates: readonly string[]; reason: string }>
> = {
  "De geruchten\u0000Hugo Claus": { candidates: ["OL15056309W","OL34920661W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "De verwondering\u0000Hugo Claus": { candidates: ["OL15056319W","OL34847321W","OL34847322W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Het volgende verhaal\u0000Cees Nooteboom": { candidates: ["OL643733W","OL643727W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Het woud der verwachting\u0000Hella S. Haasse": { candidates: ["OL34953098W","OL1348388W","OL31807425W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Problemski Hotel\u0000Dimitri Verhulst": { candidates: ["OL866308W","OL29300266W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Vele hemels boven de zevende\u0000Griet Op de Beeck": { candidates: ["OL34832983W","OL34832981W","OL34832980W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Opwaaiende zomerjurken\u0000Oek de Jong": { candidates: ["OL1687249W","OL33764038W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Nieuwe buren\u0000Saskia Noort": { candidates: ["OL8937618W","OL29299434W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Bonuskind\u0000Saskia Noort": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Rendez-vous\u0000Esther Verhoef": { candidates: ["OL19335865W","OL27973487W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Alles te verliezen\u0000Esther Verhoef": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Alter ego\u0000Esther Verhoef": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Het laatste offer\u0000Simone van der Vlugt": { candidates: ["OL24269387W","OL33729181W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Herfstlied\u0000Simone van der Vlugt": { candidates: ["OL24269313W","OL19943872W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "In mijn dromen\u0000Simone van der Vlugt": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Nooit alleen\u0000Loes den Hollander": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "De macht van meneer Miller\u0000Charles den Tex": { candidates: ["OL26180417W","OL34885185W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Cel\u0000Charles den Tex": { candidates: ["OL34875672W","OL33763262W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Wachtwoord\u0000Charles den Tex": { candidates: ["OL45807841W","OL33763745W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Het dossier\u0000Anya Niewierra": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Vogeleiland\u0000Marion Pauw": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Pluk van de Petteflet\u0000Annie M.G. Schmidt": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Abeltje\u0000Annie M.G. Schmidt": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Wiplala\u0000Annie M.G. Schmidt": { candidates: ["OL34926590W","OL3173349W","OL29409308W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Ibbeltje\u0000Annie M.G. Schmidt": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Kinderen van Moeder Aarde\u0000Thea Beckman": { candidates: ["OL24343787W","OL26431025W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Stad in de storm\u0000Thea Beckman": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Lover of loser\u0000Carry Slee": { candidates: ["OL26178174W","OL33761237W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Kappen!\u0000Carry Slee": { candidates: ["OL20660640W","OL27677556W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Joël\u0000Carry Slee": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Foeksia de miniheks\u0000Paul van Loon": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Weerwolvenbos\u0000Paul van Loon": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Het boek van alle dingen\u0000Guus Kuijer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Honderd uur nacht\u0000Anna Woltz": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "De tunnel\u0000Anna Woltz": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Achtste-groepers huilen niet\u0000Jacques Vriens": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Oorlogsgeheimen\u0000Jacques Vriens": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Groep acht aan de macht\u0000Jacques Vriens": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "De brug\u0000Geert Mak": { candidates: ["OL20112304W","OL34832377W","OL34832378W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Gratis geld voor iedereen\u0000Rutger Bregman": { candidates: ["OL31712603W","OL30708943W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "De meeste mensen deugen\u0000Rutger Bregman": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Morele ambitie\u0000Rutger Bregman": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Anna\u0000Annejet van der Zijl": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Sonny Boy\u0000Annejet van der Zijl": { candidates: ["OL759017W","OL36528810W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "De Amerikaanse prinses\u0000Annejet van der Zijl": { candidates: ["OL24447276W","OL37992490W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Anna Boom\u0000Judith Koelemeijer": { candidates: ["OL34536597W","OL34536598W","OL34536599W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Etty Hillesum\u0000Judith Koelemeijer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Het zijn net mensen\u0000Joris Luyendijk": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Revolusi\u0000David Van Reybrouck": { candidates: ["OL37571772W","OL37585060W","OL24234444W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Wij zijn ons brein\u0000Dick Swaab": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Ons creatieve brein\u0000Dick Swaab": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Moederland\u0000Marcia Luyten": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "De Bourgondiërs\u0000Bart Van Loo": { candidates: ["OL34943539W","OL30451396W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "De omwenteling\u0000Suzanna Jansen": { candidates: ["OL34961957W","OL34961956W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Zwaar verliefd!\u0000Chantal van Gastel": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Zoek het maar uit\u0000Chantal van Gastel": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Ik wist het\u0000Chantal van Gastel": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Helemaal het einde\u0000Lisette Jonkman": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Onbreekbaar\u0000Lisette Jonkman": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Alles op alles\u0000Marijke Vos": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Van Chanel naar flanel\u0000Marijke Vos": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Wedden dat ik blijf\u0000Marijke Vos": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Ik pleit voor jou\u0000Marijke Vos": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Zes maanden zonder\u0000Charlotte de Monchy": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Eens gegeven\u0000Charlotte de Monchy": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "De kleine Johannes\u0000Frederik van Eeden": { candidates: ["OL28124824W","OL27339889W","OL36065889W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Pijpelijntjes\u0000Jacob Israël de Haan": { candidates: ["OL36323911W","OL3698641W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Bint\u0000F. Bordewijk": { candidates: ["OL37342453W","OL1355514W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Kaas\u0000Willem Elsschot": { candidates: ["OL1232228W","OL11819842W","OL43658254W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Het dwaallicht\u0000Willem Elsschot": { candidates: ["OL23961881W","OL11819845W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "Ivanov\u0000Hanna Bervoets": { candidates: ["OL37964331W","OL39116342W","OL45042277W"], reason: "Open Library bevat meerdere vergelijkbare work-clusters zonder overtuigend canoniek hoofdrecord." },
  "De Mitsukoshi Troostbaby Company\u0000Auke Hulst": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "De eilanden\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Zuidenwind\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Sneeuwexpress\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Lentevuur\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Souvenir\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Waterland\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Midwinter\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Koraalrif\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Nachtvorst\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Gletsjer\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Strandfeest\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "De vallei\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Mayday\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Sneeuwstorm\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Bloemeneiland\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Nachtvlucht\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Festival\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Ingesneeuwd\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Onderstroom\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Zomeravond\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Dwaalspoor\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Sterrennacht\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Vakantiegeld\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "De scheiding\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Een vluchtig gebaar\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "Madonna\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
  "In de mist\u0000Suzanne Vermeer": { candidates: [], reason: "Geen betrouwbare exacte titel-auteurmatch in Open Library gevonden." },
};

const openLibraryMetadata = (title: string, author: string) => {
  const key = seedKey(title, author);
  const expectedOpenLibraryWorkId = OPEN_LIBRARY_WORK_IDS[key];
  const expectedOpenLibraryAuthorId = OPEN_LIBRARY_AUTHOR_IDS[key];
  const review = MANUAL_REVIEWS[key];
  const matchOverrides = OPEN_LIBRARY_MATCH_OVERRIDES[key];
  const nativeDisposition = NETHERLANDS_NATIVE_DISPOSITIONS[key];
  return {
    ...(expectedOpenLibraryWorkId ? { expectedOpenLibraryWorkId } : {}),
    ...(expectedOpenLibraryAuthorId ? { expectedOpenLibraryAuthorId } : {}),
    ...matchOverrides,
    ...(nativeDisposition?.status === 'LUMISCORE_NATIVE_READY'
      ? { nativeMetadata: nativeDisposition }
      : nativeDisposition
        ? {
            importDisposition: nativeDisposition.status,
            dispositionReason: nativeDisposition.reason,
          }
        : {}),
    ...(!expectedOpenLibraryWorkId && !nativeDisposition && review
      ? {
          manualReviewCandidates: review.candidates,
          manualReviewReason: review.reason,
        }
      : {}),
  };
};

const core = (
  title: string,
  author: string,
  firstPublishYear: number,
  netherlandsCategory: NetherlandsSeedCategory,
): NetherlandsSeedBook => ({
  title,
  author,
  firstPublishYear,
  netherlandsCategory,
  collection: 'netherlands-core',
  ...openLibraryMetadata(title, author),
  category:
    netherlandsCategory === 'literary-general-fiction'
      ? 'contemporary-general-fiction'
      : netherlandsCategory === 'romance-feelgood'
        ? 'romance'
        : netherlandsCategory,
});

const suzanne = (
  title: string,
  firstPublishYear: number,
): NetherlandsSeedBook => ({
  title,
  author: 'Suzanne Vermeer',
  firstPublishYear,
  netherlandsCategory: 'thriller-crime',
  collection: 'suzanne-vermeer',
  ...openLibraryMetadata(title, 'Suzanne Vermeer'),
  category: 'thriller-crime',
});

export const NETHERLANDS_CORE_SEEDS: readonly NetherlandsSeedBook[] = [
  // Literary / general fiction (65)
  core('De ontdekking van de hemel', 'Harry Mulisch', 1992, 'literary-general-fiction'),
  core('De aanslag', 'Harry Mulisch', 1982, 'literary-general-fiction'),
  core('Twee vrouwen', 'Harry Mulisch', 1975, 'literary-general-fiction'),
  core('Het stenen bruidsbed', 'Harry Mulisch', 1959, 'literary-general-fiction'),
  core('De procedure', 'Harry Mulisch', 1998, 'literary-general-fiction'),
  core('De donkere kamer van Damokles', 'Willem Frederik Hermans', 1958, 'literary-general-fiction'),
  core('Nooit meer slapen', 'Willem Frederik Hermans', 1966, 'literary-general-fiction'),
  core('Onder professoren', 'Willem Frederik Hermans', 1975, 'literary-general-fiction'),
  core('Au pair', 'Willem Frederik Hermans', 1989, 'literary-general-fiction'),
  core('Herinneringen van een engelbewaarder', 'Willem Frederik Hermans', 1971, 'literary-general-fiction'),
  core('De avonden', 'Gerard Reve', 1947, 'literary-general-fiction'),
  core('Op weg naar het einde', 'Gerard Reve', 1963, 'literary-general-fiction'),
  core('Nader tot U', 'Gerard Reve', 1966, 'literary-general-fiction'),
  core('Moeder en zoon', 'Gerard Reve', 1980, 'literary-general-fiction'),
  core('Bezorgde ouders', 'Gerard Reve', 1988, 'literary-general-fiction'),
  core('Het verdriet van België', 'Hugo Claus', 1983, 'literary-general-fiction'),
  core('De geruchten', 'Hugo Claus', 1996, 'literary-general-fiction'),
  core('De verwondering', 'Hugo Claus', 1962, 'literary-general-fiction'),
  core('Omtrent Deedee', 'Hugo Claus', 1963, 'literary-general-fiction'),
  core('Rituelen', 'Cees Nooteboom', 1980, 'literary-general-fiction'),
  core('Het volgende verhaal', 'Cees Nooteboom', 1991, 'literary-general-fiction'),
  core('Allerzielen', 'Cees Nooteboom', 1998, 'literary-general-fiction'),
  core('Paradijs verloren', 'Cees Nooteboom', 2004, 'literary-general-fiction'),
  core('Oeroeg', 'Hella S. Haasse', 1948, 'literary-general-fiction'),
  core('Het woud der verwachting', 'Hella S. Haasse', 1949, 'literary-general-fiction'),
  core('Heren van de thee', 'Hella S. Haasse', 1992, 'literary-general-fiction'),
  core('De scharlaken stad', 'Hella S. Haasse', 1952, 'literary-general-fiction'),
  core('Het diner', 'Herman Koch', 2009, 'literary-general-fiction'),
  core('Zomerhuis met zwembad', 'Herman Koch', 2011, 'literary-general-fiction'),
  core('Geachte heer M.', 'Herman Koch', 2014, 'literary-general-fiction'),
  core('De greppel', 'Herman Koch', 2016, 'literary-general-fiction'),
  core('Joe Speedboot', 'Tommy Wieringa', 2005, 'literary-general-fiction'),
  core('Dit zijn de namen', 'Tommy Wieringa', 2012, 'literary-general-fiction'),
  core('Caesarion', 'Tommy Wieringa', 2009, 'literary-general-fiction'),
  core('De heilige Rita', 'Tommy Wieringa', 2017, 'literary-general-fiction'),
  core('La Superba', 'Ilja Leonard Pfeijffer', 2013, 'literary-general-fiction'),
  core('Grand Hotel Europa', 'Ilja Leonard Pfeijffer', 2018, 'literary-general-fiction'),
  core('Alkibiades', 'Ilja Leonard Pfeijffer', 2023, 'literary-general-fiction'),
  core('Peachez, een romance', 'Ilja Leonard Pfeijffer', 2017, 'literary-general-fiction'),
  core('Blauwe maandagen', 'Arnon Grunberg', 1994, 'literary-general-fiction'),
  core('Tirza', 'Arnon Grunberg', 2006, 'literary-general-fiction'),
  core('De asielzoeker', 'Arnon Grunberg', 2003, 'literary-general-fiction'),
  core('Moedervlekken', 'Arnon Grunberg', 2016, 'literary-general-fiction'),
  core('Het smelt', 'Lize Spit', 2016, 'literary-general-fiction'),
  core('Ik ben er niet', 'Lize Spit', 2020, 'literary-general-fiction'),
  core('De helaasheid der dingen', 'Dimitri Verhulst', 2006, 'literary-general-fiction'),
  core('Problemski Hotel', 'Dimitri Verhulst', 2003, 'literary-general-fiction'),
  core('De laatkomer', 'Dimitri Verhulst', 2013, 'literary-general-fiction'),
  core('Vele hemels boven de zevende', 'Griet Op de Beeck', 2013, 'literary-general-fiction'),
  core('Kom hier dat ik u kus', 'Griet Op de Beeck', 2014, 'literary-general-fiction'),
  core('Het beste wat we hebben', 'Griet Op de Beeck', 2017, 'literary-general-fiction'),
  core('Oorlog en terpentijn', 'Stefan Hertmans', 2013, 'literary-general-fiction'),
  core('De bekeerlinge', 'Stefan Hertmans', 2016, 'literary-general-fiction'),
  core('De avond is ongemak', 'Marieke Lucas Rijneveld', 2018, 'literary-general-fiction'),
  core('Mijn lieve gunsteling', 'Marieke Lucas Rijneveld', 2020, 'literary-general-fiction'),
  core('Wees onzichtbaar', 'Murat Isik', 2017, 'literary-general-fiction'),
  core('Verloren grond', 'Murat Isik', 2012, 'literary-general-fiction'),
  core('Indische duinen', 'Adriaan van Dis', 1994, 'literary-general-fiction'),
  core('Familieziek', 'Adriaan van Dis', 2002, 'literary-general-fiction'),
  core('Een vlucht regenwulpen', "Maarten 't Hart", 1978, 'literary-general-fiction'),
  core('Het woeden der gehele wereld', "Maarten 't Hart", 1993, 'literary-general-fiction'),
  core('Bezonken rood', 'Jeroen Brouwers', 1981, 'literary-general-fiction'),
  core('Opwaaiende zomerjurken', 'Oek de Jong', 1979, 'literary-general-fiction'),
  core('De wetten', 'Connie Palmen', 1991, 'literary-general-fiction'),
  core('De zwarte met het witte hart', 'Arthur Japin', 1997, 'literary-general-fiction'),

  // Thriller / crime (40)
  core('Terug naar de kust', 'Saskia Noort', 2003, 'thriller-crime'),
  core('De eetclub', 'Saskia Noort', 2004, 'thriller-crime'),
  core('Nieuwe buren', 'Saskia Noort', 2006, 'thriller-crime'),
  core('De verbouwing', 'Saskia Noort', 2009, 'thriller-crime'),
  core('Koorts', 'Saskia Noort', 2011, 'thriller-crime'),
  core('Debet', 'Saskia Noort', 2013, 'thriller-crime'),
  core('Huidpijn', 'Saskia Noort', 2016, 'thriller-crime'),
  core('Stromboli', 'Saskia Noort', 2018, 'thriller-crime'),
  core('Bonuskind', 'Saskia Noort', 2020, 'thriller-crime'),
  core('Rendez-vous', 'Esther Verhoef', 2006, 'thriller-crime'),
  core('Close-up', 'Esther Verhoef', 2007, 'thriller-crime'),
  core('Alles te verliezen', 'Esther Verhoef', 2008, 'thriller-crime'),
  core('Déjà vu', 'Esther Verhoef', 2010, 'thriller-crime'),
  core('Tegenlicht', 'Esther Verhoef', 2012, 'thriller-crime'),
  core('De kraamhulp', 'Esther Verhoef', 2014, 'thriller-crime'),
  core('Lieve mama', 'Esther Verhoef', 2015, 'thriller-crime'),
  core('Nazomer', 'Esther Verhoef', 2017, 'thriller-crime'),
  core('De nachtdienst', 'Esther Verhoef', 2021, 'thriller-crime'),
  core('Alter ego', 'Esther Verhoef', 2023, 'thriller-crime'),
  core('De reünie', 'Simone van der Vlugt', 2004, 'thriller-crime'),
  core('Schaduwzuster', 'Simone van der Vlugt', 2005, 'thriller-crime'),
  core('Het laatste offer', 'Simone van der Vlugt', 2007, 'thriller-crime'),
  core('Blauw water', 'Simone van der Vlugt', 2008, 'thriller-crime'),
  core('Herfstlied', 'Simone van der Vlugt', 2009, 'thriller-crime'),
  core('Op klaarlichte dag', 'Simone van der Vlugt', 2010, 'thriller-crime'),
  core('In mijn dromen', 'Simone van der Vlugt', 2011, 'thriller-crime'),
  core('Vrijdag', 'Loes den Hollander', 2008, 'thriller-crime'),
  core('Zwanenzang', 'Loes den Hollander', 2010, 'thriller-crime'),
  core('Dwaalspoor', 'Loes den Hollander', 2011, 'thriller-crime'),
  core('Nooit alleen', 'Loes den Hollander', 2013, 'thriller-crime'),
  core('Voorbedacht', 'Loes den Hollander', 2014, 'thriller-crime'),
  core('De macht van meneer Miller', 'Charles den Tex', 2005, 'thriller-crime'),
  core('Cel', 'Charles den Tex', 2008, 'thriller-crime'),
  core('Wachtwoord', 'Charles den Tex', 2010, 'thriller-crime'),
  core('Het dossier', 'Anya Niewierra', 2017, 'thriller-crime'),
  core('Het bloemenmeisje', 'Anya Niewierra', 2020, 'thriller-crime'),
  core('De Camino', 'Anya Niewierra', 2021, 'thriller-crime'),
  core('De nomade', 'Anya Niewierra', 2024, 'thriller-crime'),
  core('Daglicht', 'Marion Pauw', 2008, 'thriller-crime'),
  core('Vogeleiland', 'Marion Pauw', 2021, 'thriller-crime'),

  // Young adult / children (55)
  core('Pluk van de Petteflet', 'Annie M.G. Schmidt', 1971, 'young-adult-children'),
  core('Minoes', 'Annie M.G. Schmidt', 1970, 'young-adult-children'),
  core('Abeltje', 'Annie M.G. Schmidt', 1953, 'young-adult-children'),
  core('Otje', 'Annie M.G. Schmidt', 1980, 'young-adult-children'),
  core('Wiplala', 'Annie M.G. Schmidt', 1957, 'young-adult-children'),
  core('Ibbeltje', 'Annie M.G. Schmidt', 1962, 'young-adult-children'),
  core('De brief voor de koning', 'Tonke Dragt', 1962, 'young-adult-children'),
  core('Geheimen van het Wilde Woud', 'Tonke Dragt', 1965, 'young-adult-children'),
  core('De torens van februari', 'Tonke Dragt', 1973, 'young-adult-children'),
  core('Ogen van tijgers', 'Tonke Dragt', 1982, 'young-adult-children'),
  core('Aan de andere kant van de deur', 'Tonke Dragt', 1992, 'young-adult-children'),
  core('De zevensprong', 'Tonke Dragt', 1966, 'young-adult-children'),
  core('Kruistocht in spijkerbroek', 'Thea Beckman', 1973, 'young-adult-children'),
  core('Geef me de ruimte!', 'Thea Beckman', 1976, 'young-adult-children'),
  core('Triomf van de verschroeide aarde', 'Thea Beckman', 1977, 'young-adult-children'),
  core('Het rad van fortuin', 'Thea Beckman', 1978, 'young-adult-children'),
  core('Kinderen van Moeder Aarde', 'Thea Beckman', 1985, 'young-adult-children'),
  core('Het helse paradijs', 'Thea Beckman', 1987, 'young-adult-children'),
  core('Het Gulden Vlies van Thule', 'Thea Beckman', 1989, 'young-adult-children'),
  core('Hasse Simonsdochter', 'Thea Beckman', 1983, 'young-adult-children'),
  core('Stad in de storm', 'Thea Beckman', 1979, 'young-adult-children'),
  core('Koning van Katoren', 'Jan Terlouw', 1971, 'young-adult-children'),
  core('Oorlogswinter', 'Jan Terlouw', 1972, 'young-adult-children'),
  core('Briefgeheim', 'Jan Terlouw', 1973, 'young-adult-children'),
  core('Oosterschelde windkracht 10', 'Jan Terlouw', 1976, 'young-adult-children'),
  core('Pjotr', 'Jan Terlouw', 1970, 'young-adult-children'),
  core('Zoektocht in Katoren', 'Jan Terlouw', 2007, 'young-adult-children'),
  core('Spijt!', 'Carry Slee', 1996, 'young-adult-children'),
  core('Afblijven', 'Carry Slee', 1998, 'young-adult-children'),
  core('Razend', 'Carry Slee', 2000, 'young-adult-children'),
  core('Paniek', 'Carry Slee', 2001, 'young-adult-children'),
  core('Lover of loser', 'Carry Slee', 2006, 'young-adult-children'),
  core('Kappen!', 'Carry Slee', 1999, 'young-adult-children'),
  core('Brainwash', 'Carry Slee', 2012, 'young-adult-children'),
  core('Joël', 'Carry Slee', 2011, 'young-adult-children'),
  core('De griezelbus', 'Paul van Loon', 1991, 'young-adult-children'),
  core('Dolfje Weerwolfje', 'Paul van Loon', 1996, 'young-adult-children'),
  core('Foeksia de miniheks', 'Paul van Loon', 1989, 'young-adult-children'),
  core('Meester Kikker', 'Paul van Loon', 1995, 'young-adult-children'),
  core('Raveleijn', 'Paul van Loon', 2011, 'young-adult-children'),
  core('Weerwolvenbos', 'Paul van Loon', 2003, 'young-adult-children'),
  core('Het boek van alle dingen', 'Guus Kuijer', 2004, 'young-adult-children'),
  core('Op je kop in de prullenbak', 'Guus Kuijer', 1977, 'young-adult-children'),
  core('Krassen in het tafelblad', 'Guus Kuijer', 1978, 'young-adult-children'),
  core('Voor altijd samen, amen', 'Guus Kuijer', 1999, 'young-adult-children'),
  core('Honderd uur nacht', 'Anna Woltz', 2014, 'young-adult-children'),
  core('Gips', 'Anna Woltz', 2015, 'young-adult-children'),
  core('Alaska', 'Anna Woltz', 2016, 'young-adult-children'),
  core('Lampje', 'Annet Schaap', 2017, 'young-adult-children'),
  core('De tunnel', 'Anna Woltz', 2021, 'young-adult-children'),
  core('Achtste-groepers huilen niet', 'Jacques Vriens', 1999, 'young-adult-children'),
  core('Oorlogsgeheimen', 'Jacques Vriens', 2007, 'young-adult-children'),
  core('Groep acht aan de macht', 'Jacques Vriens', 1988, 'young-adult-children'),
  core('De kinderen van het Achtste Woud', 'Els Pelgrom', 1977, 'young-adult-children'),
  core('Kleine Sofie en Lange Wapper', 'Els Pelgrom', 1984, 'young-adult-children'),

  // Non-fiction (35)
  core('Hoe God verdween uit Jorwerd', 'Geert Mak', 1996, 'non-fiction'),
  core('De eeuw van mijn vader', 'Geert Mak', 1999, 'non-fiction'),
  core('In Europa', 'Geert Mak', 2004, 'non-fiction'),
  core('Reizen zonder John', 'Geert Mak', 2012, 'non-fiction'),
  core('Grote verwachtingen', 'Geert Mak', 2019, 'non-fiction'),
  core('De brug', 'Geert Mak', 2007, 'non-fiction'),
  core('De geschiedenis van de vooruitgang', 'Rutger Bregman', 2013, 'non-fiction'),
  core('Gratis geld voor iedereen', 'Rutger Bregman', 2014, 'non-fiction'),
  core('De meeste mensen deugen', 'Rutger Bregman', 2019, 'non-fiction'),
  core('Morele ambitie', 'Rutger Bregman', 2024, 'non-fiction'),
  core('Jagtlust', 'Annejet van der Zijl', 1998, 'non-fiction'),
  core('Anna', 'Annejet van der Zijl', 2002, 'non-fiction'),
  core('Sonny Boy', 'Annejet van der Zijl', 2004, 'non-fiction'),
  core('Bernhard', 'Annejet van der Zijl', 2010, 'non-fiction'),
  core('Gerard Heineken', 'Annejet van der Zijl', 2014, 'non-fiction'),
  core('De Amerikaanse prinses', 'Annejet van der Zijl', 2015, 'non-fiction'),
  core("Fortuna's kinderen", 'Annejet van der Zijl', 2021, 'non-fiction'),
  core('Het zwijgen van Maria Zachea', 'Judith Koelemeijer', 2001, 'non-fiction'),
  core('Anna Boom', 'Judith Koelemeijer', 2008, 'non-fiction'),
  core('Hemelvaart', 'Judith Koelemeijer', 2013, 'non-fiction'),
  core('Etty Hillesum', 'Judith Koelemeijer', 2022, 'non-fiction'),
  core('Het zijn net mensen', 'Joris Luyendijk', 2006, 'non-fiction'),
  core('Dit kan niet waar zijn', 'Joris Luyendijk', 2015, 'non-fiction'),
  core('De zeven vinkjes', 'Joris Luyendijk', 2022, 'non-fiction'),
  core('Congo', 'David Van Reybrouck', 2010, 'non-fiction'),
  core('Tegen verkiezingen', 'David Van Reybrouck', 2013, 'non-fiction'),
  core('Revolusi', 'David Van Reybrouck', 2020, 'non-fiction'),
  core('Wij zijn ons brein', 'Dick Swaab', 2010, 'non-fiction'),
  core('Ons creatieve brein', 'Dick Swaab', 2016, 'non-fiction'),
  core("'t Hooge Nest", 'Roxane van Iperen', 2018, 'non-fiction'),
  core('Het geluk van Limburg', 'Marcia Luyten', 2015, 'non-fiction'),
  core('Moederland', 'Marcia Luyten', 2023, 'non-fiction'),
  core('De Bourgondiërs', 'Bart Van Loo', 2019, 'non-fiction'),
  core('Het pauperparadijs', 'Suzanna Jansen', 2008, 'non-fiction'),
  core('De omwenteling', 'Suzanna Jansen', 2022, 'non-fiction'),

  // Romance / feelgood (25)
  core('Komt een vrouw bij de dokter', 'Kluun', 2003, 'romance-feelgood'),
  core('De weduwnaar', 'Kluun', 2006, 'romance-feelgood'),
  core('Pogingen iets van het leven te maken', 'Hendrik Groen', 2014, 'romance-feelgood'),
  core('Zolang er leven is', 'Hendrik Groen', 2016, 'romance-feelgood'),
  core('Leven en laten leven', 'Hendrik Groen', 2018, 'romance-feelgood'),
  core('Opgewekt naar de eindstreep', 'Hendrik Groen', 2020, 'romance-feelgood'),
  core('Zwaar verliefd!', 'Chantal van Gastel', 2008, 'romance-feelgood'),
  core('Zwaar beproefd!', 'Chantal van Gastel', 2010, 'romance-feelgood'),
  core('Geknipt voor jou', 'Chantal van Gastel', 2010, 'romance-feelgood'),
  core('Zoek het maar uit', 'Chantal van Gastel', 2011, 'romance-feelgood'),
  core('Zomer in New York', 'Chantal van Gastel', 2012, 'romance-feelgood'),
  core('Ik wist het', 'Chantal van Gastel', 2014, 'romance-feelgood'),
  core('Glazuur', 'Lisette Jonkman', 2011, 'romance-feelgood'),
  core('Verkikkerd', 'Lisette Jonkman', 2013, 'romance-feelgood'),
  core('Verslingerd', 'Lisette Jonkman', 2014, 'romance-feelgood'),
  core('Helemaal het einde', 'Lisette Jonkman', 2017, 'romance-feelgood'),
  core('Onbreekbaar', 'Lisette Jonkman', 2018, 'romance-feelgood'),
  core('Alles op alles', 'Marijke Vos', 2018, 'romance-feelgood'),
  core('Van Chanel naar flanel', 'Marijke Vos', 2019, 'romance-feelgood'),
  core('Wedden dat ik blijf', 'Marijke Vos', 2020, 'romance-feelgood'),
  core('Ik pleit voor jou', 'Marijke Vos', 2022, 'romance-feelgood'),
  core('Zes maanden zonder', 'Charlotte de Monchy', 2014, 'romance-feelgood'),
  core('Enkeltje Ierland', 'Charlotte de Monchy', 2015, 'romance-feelgood'),
  core('Eens gegeven', 'Charlotte de Monchy', 2016, 'romance-feelgood'),
  core('Nee heb je', 'Charlotte de Monchy', 2018, 'romance-feelgood'),

  // Classics (20)
  core('Max Havelaar', 'Multatuli', 1860, 'classics'),
  core('Eline Vere', 'Louis Couperus', 1889, 'classics'),
  core('De stille kracht', 'Louis Couperus', 1900, 'classics'),
  core('Van oude mensen, de dingen die voorbijgaan', 'Louis Couperus', 1906, 'classics'),
  core('Noodlot', 'Louis Couperus', 1890, 'classics'),
  core('De kleine Johannes', 'Frederik van Eeden', 1887, 'classics'),
  core('Van de koele meren des doods', 'Frederik van Eeden', 1900, 'classics'),
  core('De uitvreter', 'Nescio', 1911, 'classics'),
  core('Titaantjes', 'Nescio', 1915, 'classics'),
  core('Pijpelijntjes', 'Jacob Israël de Haan', 1904, 'classics'),
  core('Bint', 'F. Bordewijk', 1934, 'classics'),
  core('Karakter', 'F. Bordewijk', 1938, 'classics'),
  core('Knorrende beesten', 'F. Bordewijk', 1933, 'classics'),
  core('Terug tot Ina Damman', 'Simon Vestdijk', 1934, 'classics'),
  core('De koperen tuin', 'Simon Vestdijk', 1950, 'classics'),
  core('De tienduizend dingen', 'Maria Dermoût', 1955, 'classics'),
  core('Kaas', 'Willem Elsschot', 1933, 'classics'),
  core('Het dwaallicht', 'Willem Elsschot', 1946, 'classics'),
  core('Villa des Roses', 'Willem Elsschot', 1913, 'classics'),
  core('Kees de jongen', 'Theo Thijssen', 1923, 'classics'),

  // Fantasy / science fiction / speculative (10)
  core('HEX', 'Thomas Olde Heuvelt', 2013, 'fantasy-science-fiction'),
  core('Echo', 'Thomas Olde Heuvelt', 2019, 'fantasy-science-fiction'),
  core('Orakel', 'Thomas Olde Heuvelt', 2021, 'fantasy-science-fiction'),
  core('November', 'Thomas Olde Heuvelt', 2022, 'fantasy-science-fiction'),
  core('Alles wat er was', 'Hanna Bervoets', 2013, 'fantasy-science-fiction'),
  core('Ivanov', 'Hanna Bervoets', 2016, 'fantasy-science-fiction'),
  core('En ik herinner me Titus Broederland', 'Auke Hulst', 2016, 'fantasy-science-fiction'),
  core('De Mitsukoshi Troostbaby Company', 'Auke Hulst', 2021, 'fantasy-science-fiction'),
  core('Quarantaine', 'Wytske Versteeg', 2015, 'fantasy-science-fiction'),
  core('KliFi', 'Adriaan van Dis', 2021, 'fantasy-science-fiction'),
];

export const SUZANNE_VERMEER_SEEDS: readonly NetherlandsSeedBook[] = [
  suzanne('All-inclusive', 2006),
  suzanne('De vlucht', 2008),
  suzanne('Zomertijd', 2008),
  suzanne('Cruise', 2009),
  suzanne('Après-ski', 2009),
  suzanne('De suite', 2010),
  suzanne('Zwarte piste', 2011),
  suzanne('Bella Italia', 2012),
  suzanne('Bon Bini Beach', 2012),
  suzanne('Noorderlicht', 2013),
  suzanne('Het chalet', 2013),
  suzanne('Route du soleil', 2013),
  suzanne('Goudkust', 2014),
  suzanne('Mont Blanc', 2015),
  suzanne('Costa del Sol', 2015),
  suzanne('Sneeuwengelen', 2015),
  suzanne('Hittegolf', 2016),
  suzanne('Lawinegevaar', 2016),
  suzanne('Het paradijs', 2017),
  suzanne('Super de luxe', 2018),
  suzanne('IJskoud', 2018),
  suzanne('Winternacht', 2018),
  suzanne('Het strandhuis', 2019),
  suzanne('De eilanden', 2019),
  suzanne('Zuidenwind', 2020),
  suzanne('Sneeuwexpress', 2019),
  suzanne('Lentevuur', 2021),
  suzanne('Souvenir', 2021),
  suzanne('Roadtrip', 2022),
  suzanne('Waterland', 2022),
  suzanne('Midwinter', 2022),
  suzanne('Koraalrif', 2023),
  suzanne('Nachtvorst', 2023),
  suzanne('Gletsjer', 2023),
  suzanne('Strandfeest', 2023),
  suzanne('De vallei', 2023),
  suzanne('Mayday', 2023),
  suzanne('Spoorloos', 2024),
  suzanne('Sneeuwstorm', 2024),
  suzanne('Bloemeneiland', 2024),
  suzanne('Flamingo Beach', 2024),
  suzanne('Nachtvlucht', 2025),
  suzanne('Festival', 2025),
  suzanne('Ingesneeuwd', 2025),
  suzanne('Onderstroom', 2026),
  suzanne('Zomeravond', 2026),
  suzanne('Dwaalspoor', 2026),
  suzanne('Sterrennacht', 2022),
  suzanne('Vakantiegeld', 2013),
  suzanne('De scheiding', 2013),
  suzanne('Een vluchtig gebaar', 2013),
  suzanne('Madonna', 2013),
  suzanne('In de mist', 2013),
];

export const NETHERLANDS_SEEDS: readonly NetherlandsSeedBook[] = [
  ...NETHERLANDS_CORE_SEEDS,
  ...SUZANNE_VERMEER_SEEDS,
];
